services:

  postgres:
    image: postgres:17-alpine

    container_name: inventory-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: inventory-backend

    restart: always

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@postgres:5432/inventory_db

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend

    container_name: inventory-frontend

    restart: always

    depends_on:
      - backend

    environment:
      VITE_API_URL: http://localhost:8000/api/v1

    ports:
      - "5173:5173"

volumes:
  postgres_data: